{{ if .Values.rbac.install }}
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.rbac.serviceAccountName }}
{{ include "vk.labels" . | indent 2 }}
{{ end }}
